# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "335f2a536c3bcb46c4450e5ecaa080b1"
name = "Combo Product"
application_url = "https://combo-products.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://combo-products.vercel.app"
subpath = "combo-builder"
prefix = "apps"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"


[access_scopes]
scopes = "write_products,read_products,read_orders,read_inventory,read_themes,write_themes,read_publications,write_publications"

[auth]
redirect_urls = [
  "https://combo-products.vercel.app/auth/callback",
  "https://combo-products.vercel.app/shopify/callback",
  "https://combo-products.vercel.app/api/auth/callback"
]
